services:
  terraform:
    image: hashicorp/terraform
    container_name: terraform
    environment:
      - TF_DATA_DIR=/data
    volumes:
      - .:/config
      - ./data:/data
    working_dir: /config/envs/${TERRAFORM_ENV}
